#!/bin/bash
# Enrich -> rebuild -> build -> push for one pair. Safe to run repeatedly: it only
# commits when the site data actually changed, so a no-op run leaves no commit.
#   ./pipeline/deploy_youtube.sh chornobyl
set -u
cd /Users/tati/Desktop/ivan/kyivnotkiev
PAIR="${1:?usage: deploy_youtube.sh <pair>}"
KEY=$(gcloud services api-keys get-key-string 029b0141-1889-4665-a569-36d75c0f6191 \
      --project=kyivnotkiev-yt --format='value(keyString)' 2>/dev/null)
[ -z "$KEY" ] && { echo "FAIL: no API key"; exit 1; }

echo "STEP enrich $PAIR"
/opt/anaconda3/bin/python -u -m pipeline.ingestion.youtube_enrich --pair "$PAIR" --api-key "$KEY" \
  | tail -6 || { echo "FAIL: enrich"; exit 1; }

echo "STEP rebuild"
YOUTUBE_API_KEY="$KEY" /opt/anaconda3/bin/python -m pipeline.rebuild 2>&1 \
  | grep -E "ALL GOOD|issues found|ERROR" || { echo "FAIL: rebuild"; exit 1; }

echo "STEP site build"
( cd site && npx astro build 2>&1 | grep -E "Complete!|error" ) || { echo "FAIL: build"; exit 1; }

if git diff --quiet site/src/data/; then
  echo "STEP no change — nothing to deploy"
else
  YEARS=$(/opt/anaconda3/bin/python - <<PY
import json,pathlib
d=[]
for y in range(2010,2027):
    ok=all((pathlib.Path(f'data/cl/raw/youtube_census/.checkpoints/{"$PAIR"}_{v}_{y}.json').exists()
            and sum(1 for m in json.loads(pathlib.Path(f'data/cl/raw/youtube_census/.checkpoints/{"$PAIR"}_{v}_{y}.json').read_text()).get('months',{}).values() if m.get('resolved'))>=12)
           for v in ('russian','ukrainian'))
    if ok: d.append(y)
print(f"{min(d)}-{max(d)}" if d else "none")
PY
)
  git add -A site/
  git commit -q -m "data: $PAIR YouTube refreshed (uniform day depth, years $YEARS)

Regenerated by pipeline/deploy_youtube.sh — enrich, rebuild, build, push.

Claude-Session: https://claude.ai/code/session_01AZLCHVV8eh8KdoS7m5ZP6m"
  git push origin main 2>&1 | tail -1
  echo "STEP deployed"
fi
echo "DONE"
